/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        inkBlue: "#0D1B2A",
        parchment: "#F5F0E8",
        justiceGold: "#C9992A",
        goldLight: "#E8BE6A",
        safe: "#1A6B4A",
        safeLight: "#E8F5EE",
        caution: "#B85C00",
        cautionLight: "#FEF3E8",
        danger: "#991B1B",
        dangerLight: "#FEF2F2",
        ink100: "#F5F0E8",
        ink200: "#E8E0D0",
        ink300: "#C5B99A",
        ink400: "#8A7A65",
        ink500: "#5C4F3A",
        ink600: "#3A2E22",
        ink700: "#1F1710",
        ink800: "#0D1B2A",
        surface0: "#FAF7F2",
        surface1: "#FFFFFF",
        surface2: "#F0EBE0",
        textPrimary: "#1A1208",
        textSecondary: "#5C4F3A",
        textMuted: "#8A7A65",
      },
      fontFamily: {
        "plex-arabic": ["IBMPlexArabic-Regular"],
        "plex-arabic-medium": ["IBMPlexArabic-Medium"],
        "plex-arabic-semibold": ["IBMPlexArabic-SemiBold"],
        "plex-sans": ["IBMPlexSans-Regular"],
        "plex-sans-medium": ["IBMPlexSans-Medium"],
        "plex-sans-semibold": ["IBMPlexSans-SemiBold"],
        "plex-mono": ["IBMPlexMono-Regular"],
      },
    },
  },
  plugins: [],
};
